services:
  - type: web
    name: code-maker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENROUTER_API_KEY
        value: YOUR_KEY_HERE  # or set this in Render Dashboard